// <auto-generated />

using BotCore.Infrastructure.Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BotCore.Infrastructure.Test.Migrations
{
    [DbContext(typeof(BotCoreTestContext))]
    internal class BotCoreTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BotCore.Core.Test.Entities.Currency", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Abbreviation")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Rate")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Scale")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Currency");
            });
#pragma warning restore 612, 618
        }
    }
}